services:
  qr-code-service:
    build:
      context: ./qr-code-service
    expose:
      - "5000"

  web:
    build:
      context: ./web
    expose:
      - "80"
    environment:
      QR_CODE_GENERATOR_BASE_URL: https://qr.clownfish-production.de
      QR_CODE_GENERATOR_QR_CODE_SERVICE_ADDRESS: qr-code-service:5000
    depends_on:
      - qr-code-service
